config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    namespace :admin do
      resources :admin_users
      scope 'supplier/:supplier_company_type' do
        resources :supplier_companies do
          get :show
        end
      end

      resource :glover_company
      resources :child_and_pet_settings
      resources :blogs
      resources :blog_categories, path: "blog_categories/:category_type"
      resources :camp_category_groups
      resources :camp_categories
      resources :camp_types
      resources :camp_car_categories
      resources :classification_day_settings
      resources :recommended_camp_items, path: "recommended_camp_items/:item_type"
      resources :date_settings, only: [ :index, :create, :update] do
        collection do
          post :create_or_update_by_day_of_week
        end
      end
      resources :camp_cars
      resources :campsites do
        collection do
          post :reload_child_and_pet_entrance_fees_form
        end

        resources :campsite_plans
      end
      resources :campsite_plans do
        collection do
          post :camsite_default_fee
          post :reload_child_and_pet_fees_form
        end
      end
      resource :autocomplete do
      end
      resources :campsite_plan_options
      resources :camp_car_options
      resources :campsite_bookings, only: [:index, :new, :create, :show, :edit, :update] do
        member do
          patch :add_note
        end
        collection do
          get :add_note_form
          post :check_remaining_quantity
          match :calculate_price, via: [:post, :patch]
        end
      end
      resources :camp_car_bookings, only: [:index, :show, :edit, :update] do
        member do
          patch :calculate_price
          patch :add_note
        end
        collection do
          get :add_note_form
        end
      end
      resources :slider_banners
      resources :contact_us, only: [:index, :show]

      resources :travel_packages, only: [] do
        member do
          patch :update_status
          delete :cancel
        end
      end
      resources :notices, path: 'notices/:item_type'
      resources :customer_user_managements, only: [:index]
      resources :campsite_sale_managements, only: [:index]
      resources :camp_car_sale_managements, only: [:index]
      resources :booking_messages, only: [:update]
      resources :states, only: [:index, :edit, :update]

      resources :deepl_translations do
        collection do
          post :translate
        end
      end

      root  to: 'admin_users#index',
            constraints: RoleConstraint.new(:super_admin),
            as: :root


      root  to: 'supplier_companies#show',
            constraints: RoleConstraint.new(:camp_car_admin),
            as: :camp_car_root,
            supplier_company_type: 'camp_car_supplier_company'

      root  to: 'supplier_companies#show',
            constraints: RoleConstraint.new(:campsite_admin),
            as: :campsite_root,
            supplier_company_type: 'campsite_supplier_company'
    end

    devise_for :admin_users
    devise_for :customer_users, controllers: { sessions: 'customer_users/sessions', registrations: 'customer_users/registrations', passwords: 'customer_users/passwords' }
    devise_scope :customer_user do
      get "customer_users/new_email_validation",
          to: "customer_users/registrations#new_email_validation",
          as: :new_email_validation

      post "customer_users/validate_email",
          to: "customer_users/registrations#validate_email",
          as: :validate_email

      get "customer_users/email_validation",
          to: "customer_users/registrations#email_validation",
          as: :email_validation

    end

    resources :bookings, only: [:index]
    resources :campsites, only: [:index, :show] do
      collection do
        get :search
      end
    end
    resources :campsite_plans, only: [:show] do
      collection do
        post :calculate_price
        post :check_remaining_quantity
      end
    end
    resources :camp_cars, only: [:index, :show] do
      collection do
        get :search
        post :calculate_price
        post :check_remaining_quantity
      end
    end
    resources :notices, only: [:index, :show]

    namespace :checkout do
      resources :member_registrations do
        collection do
          get :new_email_validation
          post :validate_email
          get :email_verification
          get :password_for_sign_in
          post :sign_in_customer_user
        end
      end

      resources :campsite_bookings, only: [:edit] do
        member do
          match :select_people_and_date, via: [:get, :post]
        end

        collection do
          get :select_plan_options
          get :contact_information
          get :confirm_information
          post :create_booking
          post :update_booking
          post :calculate_price
          post :check_remaining_quantity
          get :thank_you
        end
      end

      resources :camp_car_bookings, only: [] do
        member do
          match :select_place_and_date, via: [:get, :post]
        end

        collection do
          get :select_car_options
          get :contact_information
          get :confirm_information
          post :create_booking
          post :update_booking
          post :calculate_price
          post :check_remaining_quantity
          get :thank_you
        end
      end

      resources :payments, only: [:new, :create] do
        collection do
          get :add_card
          get :credit_card_addition_expired
        end
      end

    end

    resources :tours
    resource :my_page, only: [:show]

    resources :travel_packages, only: [:show] do
      member do
        patch :update_status
        delete :cancel
      end
    end

    resource :contact_us, only: [:new, :create] do
      collection do
        match :confirm_information, via: [:get, :post]
        get :thanks
      end
    end
    resources :blogs, only: [:index, :show], path: "blogs/:blog_type"

    resources :privacy_policy, only: [:index]
    resources :terms_of_use, only: [:index]
    resources :booking_messages, only: [:create, :show, :update]
    resource :autocomplete do
      collection do
        get :search_free_word
      end
    end

    get 'home/booking_histories', to: 'home#booking_histories'
    get 'home/contact', to: 'home#contact'
    get 'home/contact_errors', to: 'home#contact_errors'
    get 'home/contact_confirm', to: 'home#contact_confirm'
    get 'home/contact_thanks', to: 'home#contact_thanks'
    get 'rental_cars', to: 'rental_cars#index'
    get 'rental_equipments', to: 'rental_equipments#index'
    get 'information', to: 'home#information'
  end

  root 'home#index'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/camp_car.rb
class CampCar < ApplicationRecord
  include SupplierCompanyAsTenant

  acts_as_taggable_on :tags

  belongs_to :category, class_name: 'CampCarCategory'
  belongs_to :camp_car_supplier_company, foreign_key: :supplier_company_id
  belongs_to :state, class_name: 'Master::State'
  belongs_to :prefecture, class_name: 'Master::Prefecture'
  has_many :photos, as: :photoable, dependent: :destroy
  has_many :camp_car_bookings, dependent: :destroy
  has_many :camp_car_quantities, dependent: :destroy
  has_and_belongs_to_many :camp_car_options
  has_one :notice, as: :notice_itemable, dependent: :destroy
  has_many :recommended_camp_items, as: :recommended_itemable, dependent: :destroy

  translates :name, :description, :subtitle
  globalize_accessors locales: I18n.available_locales, attributes: [:name, :description, :subtitle]
  globalize_validations locales: [:ja] # Validates only 'ja' locale | https://app.clickup.com/t/1rpetz0

  validates :product_id, :name, :car_type, :category_id, :maximum_number_of_people, :fee_per_hour, :fee_per_day, presence: true
  validates :quantity, :fee_per_day, :fee_per_hour, :maximum_number_of_people, numericality: { greater_than_or_equal_to: 0 }
  # Add all your validations before
  validate :validates_globalized_attributes

  accepts_nested_attributes_for :photos, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :camp_car_quantities, reject_if: :all_blank, allow_destroy: true

  scope :only_public, -> () {where(is_public: true)}
  scope :by_state, -> (state) { where(state_id: state) }
  scope :by_prefecture, -> (prefecture) { where(prefecture_id: prefecture) }
  scope :booked_in_date_range, -> (start_date, end_date) {
    camp_car_booking = CampCarBooking.by_start_date_and_end_date(start_date, end_date)
    where(id: camp_car_booking.pluck(:camp_car_id))
  }
  scope :by_id, -> (ids) { where(id: ids) }
  scope :by_start_date_and_end_date, -> (start_date, end_date) {
    where(created_at: (start_date.in_time_zone.beginning_of_day..end_date.in_time_zone.end_of_day))
  }

  def remaining_quantity_on(date)
    # In this case, if the records were too large so loaded it's to RAM, we will use  the SQL query to the DB
    camp_car_quantity = self.camp_car_quantities.find_by(date: date)&.quantity || self.quantity
    number_of_bookings = self.camp_car_bookings.only_booked_status.by_date(date).count

    camp_car_quantity - number_of_bookings
  end

  def is_camp_car_out_of_stock?(check_in, check_out)
    (check_in..check_out).each do |date|
      return true if self.remaining_quantity_on(date) <= 0
    end

    return false
  end

  def self.available_in_date_range(start_date, end_date)
    camp_cars = all
    camp_car_ids = camp_cars.ids

    (start_date..end_date).each do |date|
      camp_cars.each do |camp_car|
        if camp_car.remaining_quantity_on(date) < 1
          camp_car_ids.delete(camp_car.id)
        end
      end
    end

    camp_cars = camp_cars.where(id: camp_car_ids)

    camp_cars
  end

  def address
  end

  def contact_number
  end

end

# == Schema Information
#
# Table name: camp_cars
#
#  id                                 :bigint           not null, primary key
#  car_type                           :string
#  description                        :text
#  fee_per_day                        :integer
#  fee_per_hour                       :integer
#  is_pick_up_and_drop_off_place_same :boolean          default(FALSE)
#  is_public                          :boolean          default(FALSE)
#  maximum_number_of_people           :integer
#  name                               :string
#  quantity                           :integer
#  subtitle                           :text
#  created_at                         :datetime         not null
#  updated_at                         :datetime         not null
#  camp_car_id                        :bigint           not null
#  category_id                        :bigint
#  prefecture_id                      :integer
#  product_id                         :string
#  state_id                           :integer
#  supplier_company_id                :integer
#
# Indexes
#
#  index_camp_cars_on_category_id  (category_id)
#

app/controllers/admin/camp_cars_controller.rb
class Admin::CampCarsController < Admin::AdminController
  before_action :set_camp_car, only: %i[show edit update destroy]
  authorize_resource

  def index
    @camp_cars = CampCar.page(params[:page]).order(created_at: :desc)
  end

  def new
    @camp_car = CampCar.new
  end

  def create
    @camp_car = CampCar.new(camp_car_params)

    if @camp_car.save
      redirect_to admin_camp_car_path(@camp_car), notice: I18n.t("controllers.created", model: CampCar.model_name.human)
    else
      render :new, alert: @camp_car.errors.full_messages
    end
  end

  def show; end

  def edit; end

  def update
    if @camp_car.update(camp_car_params)
      redirect_to admin_camp_car_path(@camp_car), notice: I18n.t("controllers.updated", model: CampCar.model_name.human)
    else
      render :edit, alert: @camp_car.errors.full_messages
    end
  end

  def destroy
    @camp_car.destroy
    redirect_to admin_camp_cars_path(), notice: I18n.t("controllers.deleted", model: CampCar.model_name.human)
  end

  private

  def camp_car_params
    while_list = [
      :product_id,
      :car_type,
      :quantity,
      :category_id,
      :tag_list,
      :maximum_number_of_people,
      :is_public,
      :fee_per_hour,
      :fee_per_day,
      :supplier_company_id,
      :state_id,
      :prefecture_id,
      photos_attributes: [:id, :image, :_destroy],
      camp_car_quantities_attributes: [
        :id, :date, :quantity, :_destroy
      ],
      camp_car_option_ids: []
    ]

    params.require(:camp_car).permit(while_list + CampCar.globalize_attribute_names)
  end

  def set_camp_car
    @camp_car = CampCar.find params[:id]
  end
end

app/controllers/camp_cars_controller.rb
class CampCarsController < ApplicationController
  include ComingSoon

  before_action :render_coming_soon

  def index
    @recommended_camp_cars = RecommendedCampItem.order_by(:camp_car, :asc).map(&:recommended_itemable)
    @blog_categories = BlogCategory.all
  end

  def search
    @camp_car_search_service = CampCarSearchService.new(params)
    @camp_cars = @camp_car_search_service.run.page(params[:page])
  end

  def calculate_price
    travel_package = TravelPackage.new()
    travel_package.assign_attributes(travel_package_params)
    booking_price_service = CampCarBookingPriceCalculationService.new(travel_package.camp_car_booking)
    travel_package.total_price = booking_price_service.calculate

    travel_package_serializable = TravelPackageSerializer.new(travel_package).serializable_hash(include: '**')
    set_travel_package_of_camp_car_booking_draft(travel_package_serializable)

    render json: travel_package_serializable
  end

  def show
    session.delete(:travel_package_of_camp_car_booking_draft)

    @camp_car = CampCar.find(params[:id])
    @notice = @camp_car.notice

    camp_car_booking_service = CampCarBookingService.new(CustomerUser.new, params)
    @travel_package = camp_car_booking_service.init_travel_package
  end

  def check_remaining_quantity
    camp_car_quantity_calculation_service = CampCarQuantityCalculationService.new(
      params, current_customer_user)

    result = camp_car_quantity_calculation_service.is_camp_car_out_of_stock?

    render json: {is_camp_car_out_of_stock: result}
  end

  private

  def set_travel_package_of_camp_car_booking_draft(travel_package_serializable)
    session[:travel_package_of_camp_car_booking_draft] = travel_package_serializable
  end

  def travel_package_params
    permitted_params = params.require(:travel_package).permit(
      camp_car_booking_attributes: [
        :id, :camp_car_id, :start_date_of_renting, :end_date_of_renting,
      ],
    )
  end
end

app/views/camp_cars/_place_and_date_selection.html.slim
.d-none
  = f.hidden_field :customer_user_id
  = f.simple_fields_for :camp_car_booking do |ff|
    = ff.hidden_field :camp_car_id
    = ff.hidden_field :start_date_of_renting, value: ff.object.start_date_of_renting.strftime('%d/%m/%Y'), class: 'start-date-of-renting-input'
    = ff.hidden_field :end_date_of_renting, value: ff.object.end_date_of_renting.strftime('%d/%m/%Y'), class: 'end-date-of-renting-input'

.row.mt-2
  .col-12
    /  5月31日月曜日-6月8日月曜日
    span#camp-car-booking-time-range.text-gray.font-12.font-weight-bold.cursor-pointer
      span.start-date-of-renting
        = f.object.camp_car_booking.start_date_of_renting.strftime('%d/%m/%Y')
      span -
      span.end-date-of-renting
        = f.object.camp_car_booking.end_date_of_renting.strftime('%d/%m/%Y')
    a#btn-edit-camp-car-booking-time-range href="javascript:void(0)" class="link-to-edit-booking float-right text-blue font-12 font-weight-bold"
      = t("checkout.camp_car_bookings.page.link_name.to_edit")

app/views/camp_cars/index.html.slim
.camp-car-container-wrapper
  section.main-banner-wrapper.mb-5
    .container
      .text-content-wrapper
        .line-1.font-36-up-lg.font-20-down-md キャンピングカーで自由な旅を
        .line-2.font-18-up-lg.font-14-down-md 全国のキャンプピングカーを検索・予約ができます
    = image_tag 'camp-site-banner.png', class: 'img-fluid'

  section.search-inputs.row.no-gutters
    .col-12.col-md-6.col-lg-5.mx-auto
      .camp-car-search-input-wrapper
        = form_with url: search_camp_cars_path(), method: :get do |f|
          = render 'shared/camp_car_search_input', f: f
          .row
            .col-12.mt-3.text-center
              button type='submit' class="btn btn-blue font-14 font-weight w-100 no-border-radius" キャンピングカーを探す

  / -> Maybe use this one again, so please don't delete
  / section.container.recommended-store
  /   .row-12.title
  /     .col-12.row-en
  /       | Recommended store
  /     .col-12.row-ja
  /       | おすすめ店舗

  /   .row.list
  /     - 3.times.each do
  /       .col-12.col-lg-4.mb-3
  /         .row.no-gutters
  /           .image-wrapper.col-5.col-lg-12
  /             = image_tag 'camp_cars/recommended_store.jpg', class: 'img-fluid'
  /           .col-7.col-lg-12.content
  /             .item
  /               a href="#" class="btn btn-green font-9 no-border-radius mt-2" 長野県
  /             .name.mt-2
  /               | アキラファクトリー
  /             .adress
  /               | 松本市深津1丁目1-1

  section.container.map-and-shorlinks.mgt-30
    .row.justify-content-center
      / -> Maybe use this one again, so please don't delete
      / .shorlinks.col-md-6.order-md-2
      /   = render 'shared/items_title',
      /           title: 'Search by Area',
      /           description: 'エリアからキャンプ場を探す'
      /    = render 'shared/blog_categories', glover_blogs: @glover_blogs

      .map.col-md-6.order-1.order-md-1
        = render 'shared/items_title',
                title: 'Search by Map',
                description: '地図からキャンプ場を探す'
        = render "shared/camp_car_map"

  section.container.recommended-camper
    .row-12.title
      .col-12.row-en
        | Recommended camper
      .col-12.row-ja
        | おすすめキャンピングカー

    .row.list.d-flex.justify-content-center
      - @recommended_camp_cars.each do |camp_car|
        .col-12.col-lg-3
          .row.no-gutters
            .image-wrapper.col-5.col-lg-12
              = link_to (gcamp_image_tag camp_car.photos.first&.image, class: 'img-fluid'), camp_car_path(camp_car)
            .col-7.col-lg-12.content
              .item
                a href="#" class="btn btn-green font-9 no-border-radius mt-2" = camp_car.prefecture.name
              .name.mt-2 = camp_car.name
              .price = "1日#{camp_car.fee_per_day}円〜"

          .border-bottom.d-lg-none

app/views/camp_cars/search.html.slim
.camp-car-search-container-wrapper
  section.main-banner-wrapper
    = image_tag 'camp-site-banner.png', class: 'img-fluid'

  section.search-inputs.row.no-gutters.mt-3
    .col-12.col-md-6.col-lg-5.mx-auto
      .camp-car-search-input-wrapper
        = form_with url: search_camp_cars_path(), method: :get do |f|
          = render 'shared/camp_car_search_input', f: f, \
            location_name: @camp_car_search_service.get_searching_location_name
          .row
            .col-12.mt-3.text-center
              button type='submit' class="btn btn-blue font-14 font-weight w-100 no-border-radius" キャンピングカーを探す

  section.container.list-camp-cars.mt-5
    .row.mb-4
      .col-12.text-center.title
        | Listing of camp cars
    .row
      .col-md-8.m-auto
        .list-camp-car-items
          - @camp_cars.each do |camp_car|
            .camp-element-item-horizontal.pt-md-2.pb-md-3
              .row.no-gutters
                .col-4.image-wrapper
                  = link_to (gcamp_image_tag camp_car.photos.first&.image, class: "img-fluid"), camp_car_path(camp_car)

                .col-8.information-wrapper.py-3.py-md-0.pl-2
                  .item-header.mb-2
                    a href="#" class="btn btn-green font-9 no-border-radius" = camp_car.prefecture.name
                    / span.font-11.date.ml-2 コメント入れられます | https://app.clickup.com/t/20r01ex
                  h3.item-content.font-15.mb-0
                    = link_to camp_car.name, camp_car_path(camp_car)
                  h5.description
                    = raw truncate_html(strip_tags(camp_car.description), length: 80, omission: '...')
                  .tags
                    - camp_car.tag_list.last(3).each do |tag|
                      span.mr-2
                        a href="#" class="btn btn-gray font-9 no-border-radius" = tag
              .border-bottom.d-md-none
    .row
      .container.pagination.justify-content-center
        = paginate @camp_cars, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm", nav_class: "d-inline-b"

app/views/camp_cars/show.html.slim
- check_in = @travel_package.camp_car_booking.start_date_of_renting.to_date
- check_out = @travel_package.camp_car_booking.end_date_of_renting.to_date
- is_camp_car_out_of_stock = @camp_car.is_camp_car_out_of_stock?(check_in, check_out)

.camp-car-detail-container-wrapper.mt-4.mt-lg-0
  .camp-car-content-wrapper
    = render 'shared/messages'
  / Display on desktop only
  section.main-slider.d-none.d-lg-block
    - if @camp_car.photos.present?
      - @camp_car.photos.last(4).each do |photo|
        .slider-item
          = image_tag photo.image.url
  / This class margin left and right is 25%
  .camp-car-content-wrapper
    / Hide on desktop only
    section.banner-wrapper.mb-2.container.d-lg-none
      .row
        .col-12
          .item-image
            - if @camp_car.photos.present?
              = image_tag @camp_car.photos.first.image.url

    section.container.auto-site-content.mt-lg-5.mt-3
      .row
        .col-12
          .title-auto-site.font-weight-bold.mt-lg-3.font-16-down-md.font-18-up-lg = @camp_car.name
      .row.mt-lg-3.mt-1
        .col-lg-7.col-12
          - @camp_car.tag_list.last(4).each do |tag|
            a href="#" class='btn btn-gray font-8 no-border-radius mr-1' = tag

        .col-lg-5.col-12
          .text-wrapper.float-right.font-weight-bold
            span.text-style.font-13-down-md.font-16-up-lg.number-of-days
              = @travel_package.camp_car_booking.number_of_nights
            span 泊
            span.text-yellow.font-20-down-md.font-28-up-lg.text-currency.total-price
              = gcamp_round_price(@travel_package.total_price)
            span.text-style.font-13-down-md.font-16-up-lg 円〜
      .row.description.mt-3.mb-lg-2.mt-1
        .col-12
          .text-description.font-11-down-md.font-14-up-lg.font-weight-bold
            = raw @camp_car.subtitle
      - if @notice.present?
        .row.news-wrapper.mt-5.mb-4.only-scr-desktop
          .col-12.text-center.mt-3.mb-1
            .i.far.fa-question-square.text-green.icon-question.font-32
          .col-12.text-center.font-16.font-weight-bold.mb-3
            = link_to @notice.title, notice_path(@notice)
          .col-12.font-13.mb-2
            = link_to (raw @notice.content), notice_path(@notice)
      .row.slider.mt-3.d-lg-none
        - if @camp_car.photos.present?
          - @camp_car.photos.each do |photo|
            .slider-item
              = image_tag photo.image.url

      .row
        .col-12.text-center.mt-2.mb-4
          = link_to t('views.buttons.booking'),
                    select_place_and_date_checkout_camp_car_booking_path(@camp_car.id),
                    class: "btn btn-w350-full-width-mobile btn-yellow font-weight-bold \
                    #{'d-none' if is_camp_car_out_of_stock}",
                    method: :post

    section.container.information-content
      .row
        .col-12
          .text-border-left.font-weight-bold.font-18 車の詳細
      .row.mt-3.mb-5
        .col-12
          = raw @camp_car.description

    section.container.plan-basic-information.mt-3
      .row
        .col-12
          .text-border-left.font-weight-bold.font-18 車の基本情報
      .row
        .col-12
          .text-blue-briny.font-12.font-weight-bold.mt-3 仕様
      .row
        .col-12
          table.table.font-weight-bold.font-9.mt-2.mb-3
            tbody
              tr
                th scope='row' = t('activerecord.attributes.camp_car.name')
                td = @camp_car.name
              tr
                th scope='row' = t('activerecord.attributes.camp_car.car_type')
                td = @camp_car.car_type
              tr
                th scope='row' = t('activerecord.attributes.camp_car_category.model')
                td = @camp_car.category.model
              tr
                th scope='row' = t('activerecord.attributes.camp_car.maximum_number_of_people')
                td = @camp_car.maximum_number_of_people
      .row
        .col-12
          .text-blue-briny.font-12.font-weight-bold プラン内容・ご利用日数
      .row
        .col-12.text-description.font-weight-bold.mt-2.mb-3
          | ・内容は変更になる場合もございます。

    section.container.select-date-content.mt-3
      .mb-5
        .row
          .col-12
            .text-border-left.font-weight-bold.font-18 日程を選択する
        .row.mt-3
          .col-12
            .text-blue-briny.font-12.font-weight-bold 予約期間

        = simple_form_for(@travel_package, url: '', html: { class: 'camp-car-booking-form'}) do |f|
          = render 'place_and_date_selection', f: f
      .row
        .col-12
          .text-wrapper.text-center.font-weight-bold
            span.text-style.font-13-down-md.font-16-up-lg.number-of-days
              = @travel_package.camp_car_booking.number_of_nights
            span 泊
            span.text-yellow.font-20-down-md.font-28-up-lg.text-currency.total-price
              = gcamp_round_price(@travel_package.total_price)
            span.text-style.font-13-down-md.font-16-up-lg 円〜

      .row.mgt-26
        .col-12.text-center
          = link_to t('views.buttons.booking'),
                    select_place_and_date_checkout_camp_car_booking_path(@camp_car.id),
                    class: "btn btn-w350-full-width-mobile btn-yellow font-weight-bold \
                            #{'d-none' if is_camp_car_out_of_stock}",
                    method: :post

        .col-12.mgt-12.text-center
          = link_to t('views.buttons.back'),
                    request.referer || camp_cars_path(),
                    class: 'btn btn-w350-full-width-mobile btn-black font-weight-bold'