config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    namespace :admin do
      resources :admin_users
      scope 'supplier/:supplier_company_type' do
        resources :supplier_companies do
          get :show
        end
      end

      resource :glover_company
      resources :child_and_pet_settings
      resources :blogs
      resources :blog_categories, path: "blog_categories/:category_type"
      resources :camp_category_groups
      resources :camp_categories
      resources :camp_types
      resources :camp_car_categories
      resources :classification_day_settings
      resources :recommended_camp_items, path: "recommended_camp_items/:item_type"
      resources :date_settings, only: [ :index, :create, :update] do
        collection do
          post :create_or_update_by_day_of_week
        end
      end
      resources :camp_cars
      resources :campsites do
        collection do
          post :reload_child_and_pet_entrance_fees_form
        end

        resources :campsite_plans
      end
      resources :campsite_plans do
        collection do
          post :camsite_default_fee
          post :reload_child_and_pet_fees_form
        end
      end
      resource :autocomplete do
      end
      resources :campsite_plan_options
      resources :camp_car_options
      resources :campsite_bookings, only: [:index, :new, :create, :show, :edit, :update] do
        member do
          patch :add_note
        end
        collection do
          get :add_note_form
          post :check_remaining_quantity
          match :calculate_price, via: [:post, :patch]
        end
      end
      resources :camp_car_bookings, only: [:index, :show, :edit, :update] do
        member do
          patch :calculate_price
          patch :add_note
        end
        collection do
          get :add_note_form
        end
      end
      resources :slider_banners
      resources :contact_us, only: [:index, :show]

      resources :travel_packages, only: [] do
        member do
          patch :update_status
          delete :cancel
        end
      end
      resources :notices, path: 'notices/:item_type'
      resources :customer_user_managements, only: [:index]
      resources :campsite_sale_managements, only: [:index]
      resources :camp_car_sale_managements, only: [:index]
      resources :booking_messages, only: [:update]
      resources :states, only: [:index, :edit, :update]

      resources :deepl_translations do
        collection do
          post :translate
        end
      end

      root  to: 'admin_users#index',
            constraints: RoleConstraint.new(:super_admin),
            as: :root


      root  to: 'supplier_companies#show',
            constraints: RoleConstraint.new(:camp_car_admin),
            as: :camp_car_root,
            supplier_company_type: 'camp_car_supplier_company'

      root  to: 'supplier_companies#show',
            constraints: RoleConstraint.new(:campsite_admin),
            as: :campsite_root,
            supplier_company_type: 'campsite_supplier_company'
    end

    devise_for :admin_users
    devise_for :customer_users, controllers: { sessions: 'customer_users/sessions', registrations: 'customer_users/registrations', passwords: 'customer_users/passwords' }
    devise_scope :customer_user do
      get "customer_users/new_email_validation",
          to: "customer_users/registrations#new_email_validation",
          as: :new_email_validation

      post "customer_users/validate_email",
          to: "customer_users/registrations#validate_email",
          as: :validate_email

      get "customer_users/email_validation",
          to: "customer_users/registrations#email_validation",
          as: :email_validation

    end

    resources :bookings, only: [:index]
    resources :campsites, only: [:index, :show] do
      collection do
        get :search
      end
    end
    resources :campsite_plans, only: [:show] do
      collection do
        post :calculate_price
        post :check_remaining_quantity
      end
    end
    resources :camp_cars, only: [:index, :show] do
      collection do
        get :search
        post :calculate_price
        post :check_remaining_quantity
      end
    end
    resources :notices, only: [:index, :show]

    namespace :checkout do
      resources :member_registrations do
        collection do
          get :new_email_validation
          post :validate_email
          get :email_verification
          get :password_for_sign_in
          post :sign_in_customer_user
        end
      end

      resources :campsite_bookings, only: [:edit] do
        member do
          match :select_people_and_date, via: [:get, :post]
        end

        collection do
          get :select_plan_options
          get :contact_information
          get :confirm_information
          post :create_booking
          post :update_booking
          post :calculate_price
          post :check_remaining_quantity
          get :thank_you
        end
      end

      resources :camp_car_bookings, only: [] do
        member do
          match :select_place_and_date, via: [:get, :post]
        end

        collection do
          get :select_car_options
          get :contact_information
          get :confirm_information
          post :create_booking
          post :update_booking
          post :calculate_price
          post :check_remaining_quantity
          get :thank_you
        end
      end

      resources :payments, only: [:new, :create] do
        collection do
          get :add_card
          get :credit_card_addition_expired
        end
      end

    end

    resources :tours
    resource :my_page, only: [:show]

    resources :travel_packages, only: [:show] do
      member do
        patch :update_status
        delete :cancel
      end
    end

    resource :contact_us, only: [:new, :create] do
      collection do
        match :confirm_information, via: [:get, :post]
        get :thanks
      end
    end
    resources :blogs, only: [:index, :show], path: "blogs/:blog_type"

    resources :privacy_policy, only: [:index]
    resources :terms_of_use, only: [:index]
    resources :booking_messages, only: [:create, :show, :update]
    resource :autocomplete do
      collection do
        get :search_free_word
      end
    end

    get 'home/booking_histories', to: 'home#booking_histories'
    get 'home/contact', to: 'home#contact'
    get 'home/contact_errors', to: 'home#contact_errors'
    get 'home/contact_confirm', to: 'home#contact_confirm'
    get 'home/contact_thanks', to: 'home#contact_thanks'
    get 'rental_cars', to: 'rental_cars#index'
    get 'rental_equipments', to: 'rental_equipments#index'
    get 'information', to: 'home#information'
  end

  root 'home#index'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @glover_blog_categories = BlogCategory.with_category_type(:glover_blog).order(created_at: :desc).limit(6)
    @supplier_blogs = Blog.without_keep_private.top_page.with_blog_type(:supplier_blog).order(created_at: :desc).limit(4)
    @home_banner = SliderBanner.latest_by(:home)
    @notices = Kaminari.paginate_array(Notice.without_keep_private.with_item_type(:super_admin).order_publish_date_desc_null_last.first(3)).page(params[:page])
  end

  def contact; end

  def contact_errors; end

  def contact_confirm; end

  def contact_thanks; end

  def information; end

end

app/helpers/home_helper.rb
module HomeHelper
  def notice_itemable_path(notice)
    if notice.item_type.campsite?
      campsite_path(notice.notice_itemable)
    elsif notice.item_type.camp_car?
      camp_car_path(notice.notice_itemable)
    else
      # TODO: tour_path
    end
  end
end

app/views/home/booking_histories.html.slim
.booking-histories-wrapper
  .container
    section.header-wrapper
      .title-wrapper.text-center
        span マイページ
      .d-flex.justify-content-center.align-items-center.mt-3.tabs-wrapper
        .position-relative.tab-button-wrapper.mr-2
          button#left-tab-button.btn.button-tab.tab-active.text-light href="#" 予約一览
        .position-relative.tab-button-wrapper.ml-2
          button#right-tab-button.btn.button-tab href="#" 会員情報
      .subtitle.text-center
        span.list-title 予約履歴一覧
        span.info-title.content-not-active 会員情報設定
    section.content-wrapper
      #left-tab-content
        = render 'shared/booking_history_items'
      #right-tab-content.content-not-active
        form.member-information-form
          .form-group.input-container.mb-4
            label for="email" メールアドレス
            input#email.form-control.pl-3.border-0 placeholder="akiraizutsu@gmail.com" type="email" /
          .form-group.input-container.mb-4
            label for="birthday"
              | 生年月日
              span.require-input-icon *
            input#birthday.form-control.pl-3.border-0 placeholder="1982年12月19日" type="text" /
          .form-group.input-container.mb-4
            label for="birthday"
              | パスワード
              span.require-input-icon *
            input#exampleInputPassword1.form-control.pl-3.border-0 placeholder="パスワード" type="text" /
          .form-group.input-container.mb-5
            label for="birthday" 電話番号
            input#exampleInputPassword1.form-control.pl-3.border-0 placeholder="07089460314" type="text" /

          .d-flex.flex-column.justify-content-center
            button.btn.btn-primary.rounded-0.border-0.change-info-btn type="submit" 会員情報を変更する
            button.btn.btn-primary.mt-3.rounded-0.border-0.return-btn 予約一覧へ戻る

app/views/home/contact.html.slim
.contact-wrapper.container
  section.header-wrapper
    .row.my-5
      .col-12.font-18.font-weight-bold.text-center お問い合わせ
  section.content-wrapper
    form.contact-information-form
      .form-group.input-container.mb-4
        label for="name"
          | お名前
          span.require-input-icon *
        input#name.form-control.pl-3.border-0 placeholder="akiraizutsu@gmail.com" type="email" /
      .form-group.input-container.mb-4
        label for="email"
          | メールアドレス
          span.require-input-icon *
        input#email.form-control.pl-3.border-0 placeholder="akiraizutsu@gmail.com" type="text" /
      .form-group.input-container.mb-4
        label for="phone_number"
          | 電話番号
          span.require-input-icon *
        input#phone_number.form-control.pl-3.border-0 placeholder="07089460314" type="text" /
      .form-group.input-container
        label for="content_of_require" お問い合わせ内容
        textarea#content_of_require.form-control.pl-3.border-0 rows='5'

      .text-center.mgt-30.mgb-78
        a href='#' class='btn btn-yellow font-weight-bold no-border-radius font-16' 内容を確認する

app/views/home/contact_confirm.html.slim
.contact-confirm-wrapper.container
  section.header-wrapper
    .row.my-5
      .col-12.font-18.font-weight-bold.text-center お問い合わせ内容ご確認
  section.content-wrapper
    .row
      .col-12.title
        | お名前
        span.require-input-icon *
      .col-12.data
        | akiraizutsu@gmail.com
    .row
      .col-12.title
        | メールアドレス
        span.require-input-icon *
      .col-12.data
        | akiraizutsu@gmail.com
    .row
      .col-12.title
        | 電話番号
        span.require-input-icon *
      .col-12.data
        | 07089460314
    .row
      .col-12.title
        | お問い合わせ内容
      .col-12.data
        | お問い合わせ内容が入ります

    .text-center.mgb-78
      a href='#' class='btn btn-yellow font-weight-bold no-border-radius font-16' 送信する

app/views/home/contact_errors.html.slim
.contact-wrapper.container
  section.header-wrapper
    .row.my-5
      .col-12.font-18.font-weight-bold.text-center 入力内容に誤りがあります
  section.content-wrapper
    form.contact-information-form
      .form-group.input-container.mb-4
        label for="name"
          | お名前
          span.require-input-icon *
        input#name.form-control.pl-3.border-0.error placeholder="akiraizutsu@gmail.com" type="email" value="必須項目です" /
      .form-group.input-container.mb-4
        label for="email"
          | メールアドレス
          span.require-input-icon *
        input#email.form-control.pl-3.border-0.error placeholder="akiraizutsu@gmail.com" type="text" value="メールアドレス形式で入力してください" /
      .form-group.input-container.mb-4
        label for="phone_number"
          | 電話番号
          span.require-input-icon *
        input#phone_number.form-control.pl-3.border-0 placeholder="07089460314" type="text" /
      .form-group.input-container
        label for="content_of_require" お問い合わせ内容
        textarea#content_of_require.form-control.pl-3.border-0 rows='5'

      .text-center.mgt-30.mgb-78
        a href='#' class='btn btn-yellow font-weight-bold no-border-radius font-16' 内容を確認する

app/views/home/contact_thanks.html.slim
.contact-wrapper.container
  section.header-wrapper
    .row.my-5
      .col-12.font-18.font-weight-bold.text-center 送信が完了しました

app/views/home/index.html.slim
/ = render "/home/session_layout"
/ = render "/home/dashboard_layout"
/ = render "/home/booking_histories"
- description t('views.project.site_description')

.home-container-wrapper
  .messages
    = render 'shared/messages'
  - if @home_banner.present?
    section.container.main-slider
      - @home_banner.photos.each do |photo|
        .slider-item
          = link_to (image_tag photo.image.url), photo.on_click_url.to_s

    section.container.secondary-slider.mb-5
      - @home_banner.photos.each do |photo|
        .slider-item
          .image-wrapper
            .overlay
            = image_tag photo.image.url

  section.container.map-and-shorlinks
    .row
      .shorlinks.col-md-6.order-md-2.mb-5
        = link_to blogs_path(blog_type: :glover_blog)
          = render 'shared/items_title',
                  title: 'Play Japan',
                  description: t('.play_japan')

        = render 'shared/blog_categories', blog_categories: @glover_blog_categories

        .text-center.mt-3
          = link_to t('.see_all_notices'), blogs_path(blog_type: :glover_blog), class: 'btn btn-primary btn-blue no-border-radius'

      .map.col-md-6.order-1.order-md-1.mb-5
        = render 'shared/items_title',
                title: 'Search by Map',
                description: t('.search_by_map')
        = render "home/japan_map"

  section.news-information.mb-5
    .container
      .row
        .col-12
          = render 'shared/items_title', title: 'Information', description: t('.notice')

      .row
        - @notices.each do |notice|
          .col-sm-6.col-md-4
            .news-item.mb-3
              = link_to notice_path(notice)
                .date = notice.publish_date&.strftime(t('datetime.with_locale.formats.short'))
                h3.title.pb-2 = notice.title
        .container.pagination.justify-content-center
          = paginate @notices, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm", nav_class: "d-inline-b"
      .text-center
        = link_to t('.see_the_list'), notices_path(item_type: :super_admin), class: 'btn btn-primary btn-blue no-border-radius'

  = render 'shared/blog_items', blogs: @supplier_blogs

app/views/home/information.html.slim
.information-page-wrapper
  .title.text-center.text-blue Information
  .sub-title
    = raw t('.sub_title')
  .date
    = raw t('.date')
  .div-img.rounder-3
    = image_tag 'information.png'
  .text-content
    = raw t('.text-content')
  .line-end
  .d-flex.justify-content-between.text-blue
    = raw t('.forward')
  .text-center
    .btn.rounder-3.mt-4.font-18.px-4.btn-blue
      = raw t('.btn')