config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    namespace :admin do
      resources :admin_users
      scope 'supplier/:supplier_company_type' do
        resources :supplier_companies do
          get :show
        end
      end

      resource :glover_company
      resources :child_and_pet_settings
      resources :blogs
      resources :blog_categories, path: "blog_categories/:category_type"
      resources :camp_category_groups
      resources :camp_categories
      resources :camp_types
      resources :camp_car_categories
      resources :classification_day_settings
      resources :recommended_camp_items, path: "recommended_camp_items/:item_type"
      resources :date_settings, only: [ :index, :create, :update] do
        collection do
          post :create_or_update_by_day_of_week
        end
      end
      resources :camp_cars
      resources :campsites do
        collection do
          post :reload_child_and_pet_entrance_fees_form
        end

        resources :campsite_plans
      end
      resources :campsite_plans do
        collection do
          post :camsite_default_fee
          post :reload_child_and_pet_fees_form
        end
      end
      resource :autocomplete do
      end
      resources :campsite_plan_options
      resources :camp_car_options
      resources :campsite_bookings, only: [:index, :new, :create, :show, :edit, :update] do
        member do
          patch :add_note
        end
        collection do
          get :add_note_form
          post :check_remaining_quantity
          match :calculate_price, via: [:post, :patch]
        end
      end
      resources :camp_car_bookings, only: [:index, :show, :edit, :update] do
        member do
          patch :calculate_price
          patch :add_note
        end
        collection do
          get :add_note_form
        end
      end
      resources :slider_banners
      resources :contact_us, only: [:index, :show]

      resources :travel_packages, only: [] do
        member do
          patch :update_status
          delete :cancel
        end
      end
      resources :notices, path: 'notices/:item_type'
      resources :customer_user_managements, only: [:index]
      resources :campsite_sale_managements, only: [:index]
      resources :camp_car_sale_managements, only: [:index]
      resources :booking_messages, only: [:update]
      resources :states, only: [:index, :edit, :update]

      resources :deepl_translations do
        collection do
          post :translate
        end
      end

      root  to: 'admin_users#index',
            constraints: RoleConstraint.new(:super_admin),
            as: :root


      root  to: 'supplier_companies#show',
            constraints: RoleConstraint.new(:camp_car_admin),
            as: :camp_car_root,
            supplier_company_type: 'camp_car_supplier_company'

      root  to: 'supplier_companies#show',
            constraints: RoleConstraint.new(:campsite_admin),
            as: :campsite_root,
            supplier_company_type: 'campsite_supplier_company'
    end

    devise_for :admin_users
    devise_for :customer_users, controllers: { sessions: 'customer_users/sessions', registrations: 'customer_users/registrations', passwords: 'customer_users/passwords' }
    devise_scope :customer_user do
      get "customer_users/new_email_validation",
          to: "customer_users/registrations#new_email_validation",
          as: :new_email_validation

      post "customer_users/validate_email",
          to: "customer_users/registrations#validate_email",
          as: :validate_email

      get "customer_users/email_validation",
          to: "customer_users/registrations#email_validation",
          as: :email_validation

    end

    resources :bookings, only: [:index]
    resources :campsites, only: [:index, :show] do
      collection do
        get :search
      end
    end
    resources :campsite_plans, only: [:show] do
      collection do
        post :calculate_price
        post :check_remaining_quantity
      end
    end
    resources :camp_cars, only: [:index, :show] do
      collection do
        get :search
        post :calculate_price
        post :check_remaining_quantity
      end
    end
    resources :notices, only: [:index, :show]

    namespace :checkout do
      resources :member_registrations do
        collection do
          get :new_email_validation
          post :validate_email
          get :email_verification
          get :password_for_sign_in
          post :sign_in_customer_user
        end
      end

      resources :campsite_bookings, only: [:edit] do
        member do
          match :select_people_and_date, via: [:get, :post]
        end

        collection do
          get :select_plan_options
          get :contact_information
          get :confirm_information
          post :create_booking
          post :update_booking
          post :calculate_price
          post :check_remaining_quantity
          get :thank_you
        end
      end

      resources :camp_car_bookings, only: [] do
        member do
          match :select_place_and_date, via: [:get, :post]
        end

        collection do
          get :select_car_options
          get :contact_information
          get :confirm_information
          post :create_booking
          post :update_booking
          post :calculate_price
          post :check_remaining_quantity
          get :thank_you
        end
      end

      resources :payments, only: [:new, :create] do
        collection do
          get :add_card
          get :credit_card_addition_expired
        end
      end

    end

    resources :tours
    resource :my_page, only: [:show]

    resources :travel_packages, only: [:show] do
      member do
        patch :update_status
        delete :cancel
      end
    end

    resource :contact_us, only: [:new, :create] do
      collection do
        match :confirm_information, via: [:get, :post]
        get :thanks
      end
    end
    resources :blogs, only: [:index, :show], path: "blogs/:blog_type"

    resources :privacy_policy, only: [:index]
    resources :terms_of_use, only: [:index]
    resources :booking_messages, only: [:create, :show, :update]
    resource :autocomplete do
      collection do
        get :search_free_word
      end
    end

    get 'home/booking_histories', to: 'home#booking_histories'
    get 'home/contact', to: 'home#contact'
    get 'home/contact_errors', to: 'home#contact_errors'
    get 'home/contact_confirm', to: 'home#contact_confirm'
    get 'home/contact_thanks', to: 'home#contact_thanks'
    get 'rental_cars', to: 'rental_cars#index'
    get 'rental_equipments', to: 'rental_equipments#index'
    get 'information', to: 'home#information'
  end

  root 'home#index'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/campsite_plan.rb
class CampsitePlan < ApplicationRecord

  I18n.available_locales.each do |locale|
    acts_as_taggable_on "tags_#{locale}"
  end

  belongs_to :campsite
  has_one :campsite_plan_fee, dependent: :destroy
  has_many :photos, as: :photoable, dependent: :destroy
  has_many :campsite_plan_daily_fee_settings, dependent: :destroy
  has_many :campsite_bookings, dependent: :destroy
  has_many :campsite_plan_quantities, dependent: :destroy

  has_and_belongs_to_many :campsite_plan_options

  translates :name, :description, :subtitle
  globalize_accessors locales: I18n.available_locales, attributes: [:name, :description, :subtitle]
  globalize_validations locales: [:ja] # Validates only 'ja' locale | https://app.clickup.com/t/1rpetz0

  accepts_nested_attributes_for :campsite_plan_fee, allow_destroy: true
  accepts_nested_attributes_for :campsite_plan_daily_fee_settings, allow_destroy: true
  accepts_nested_attributes_for :photos, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :campsite_plan_quantities, reject_if: :all_blank, allow_destroy: true

  validates_associated :campsite_plan_fee
  validates :check_in_time, :check_out_time, :max_number_of_people, :name, presence: true
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
  # Add all your validations before
  validate :validates_globalized_attributes

  scope :public_plans, -> { where(public_info: true) }
  scope :by_id, -> (ids) { where(id: ids) }
  scope :by_campsite_ids, -> (campsite_ids) { where(campsite_id: campsite_ids) }
  scope :with_campsite_translations, -> (locale) {
    includes(campsite: :translations).where(campsite_translations: {locale: locale})
  }

  def remaining_quantity(date, check_in, check_out)
    # In this case, if the records are too big to load into RAM, we will use SQL query for DB
    campsite_plan_quantity = self.campsite_plan_quantities.find_by(date: date)&.quantity || self.quantity

    # Example: campsite plan(check_in_time: 13:00, check_out_time: 11:00, default_quantity: 1),
    #          booking (check_in: 02/01/2022, check_out: 03/01/2022)
    # ==> Can create booking with check_in: 01/01/2022, check_out: 02/01/2022 and
    #     booking with check_in: 03/01/2022, check_out: 04/01/2022
    number_of_bookings = self.campsite_bookings.only_booked_status.by_date(date).count
    check_in_of_campsite_plan = '01/01/2000'.in_time_zone.change(hour: check_in_time.hour, min: check_in_time.min)
    check_out_of_campsite_plan = '01/01/2000'.in_time_zone.change(hour: check_out_time.hour, min: check_out_time.min)

    if check_in == date && check_in_of_campsite_plan >= check_out_of_campsite_plan
      number_of_bookings -= self.campsite_bookings.only_booked_status.by_check_out(date).count
    elsif check_out == date && check_in_of_campsite_plan >= check_out_of_campsite_plan
      number_of_bookings -= self.campsite_bookings.only_booked_status.by_check_in(date).count
    end

    campsite_plan_quantity - number_of_bookings
  end

  def is_campsite_plan_out_of_stock?(check_in, check_out)
    (check_in..check_out).each do |date|
      return true if remaining_quantity(date, check_in, check_out) <= 0
    end

    return false
  end

  def self.available_in_date_range(check_in, check_out)
    campsite_plans = all

    campsite_plan_ids = campsite_plans.ids
    (check_in..check_out).each do |date|
      campsite_plans.each do |campsite_plan|
        if campsite_plan.remaining_quantity(date, check_in, check_out) < 1
          campsite_plan_ids.delete(campsite_plan.id)
        end
      end
    end

    campsite_plans = campsite_plans.where(id: campsite_plan_ids)

    campsite_plans
  end

  def tags_locale_list
    send "tags_#{I18n.locale}_list"
  end

end

# == Schema Information
#
# Table name: campsite_plans
#
#  id                       :bigint           not null, primary key
#  check_in_time            :time
#  check_out_time           :time
#  description              :text
#  is_included_entrance_fee :boolean          default(TRUE)
#  max_number_of_people     :integer
#  name                     :string
#  people_type              :integer
#  public_info              :boolean
#  publication_period       :string
#  quantity                 :integer
#  subtitle                 :text
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  campsite_id              :integer
#  campsite_plan_id         :bigint           not null
#

app/controllers/campsite_plans_controller.rb
class CampsitePlansController < ApplicationController
  def show
    session.delete(:travel_package_of_campsite_booking_draft)

    @campsite_plan = CampsitePlan.find(params[:id])
    campsite_booking_service = CampsiteBookingService.new(CustomerUser.new, params)
    @travel_package = campsite_booking_service.init_travel_package
  end

  def calculate_price
    travel_package = TravelPackage.new()
    travel_package.assign_attributes(travel_package_params)
    campsite_booking = travel_package.campsite_booking
    campsite_plan_is_included_entrance_fee = campsite_booking.campsite_plan.is_included_entrance_fee

    booking_price_service = CampsiteBookingPriceCalculationService.new(
      campsite_booking,
      with_entrance_fee: !campsite_plan_is_included_entrance_fee
    )
    travel_package.total_price = booking_price_service.calculate

    travel_package_serializable = TravelPackageSerializer.new(travel_package).serializable_hash(include: '**')
    set_travel_package_of_campsite_booking_draft(travel_package_serializable)

    render json: travel_package_serializable
  end

  def check_remaining_quantity
    campsite_plan_quantity_calculation_service = CampsitePlanQuantityCalculationService.new(
      params, current_customer_user)

    result = campsite_plan_quantity_calculation_service.is_campsite_plan_out_of_stock?

    render json: {is_campsite_plan_out_of_stock: result}
  end

  private

  def set_travel_package_of_campsite_booking_draft(travel_package_serializable)
    session[:travel_package_of_campsite_booking_draft] = travel_package_serializable
  end

  def travel_package_params
    permitted_params = params.require(:travel_package).permit(
      campsite_booking_attributes: [
        :campsite_plan_id, :check_in, :check_out, :number_of_adult,
        child_and_pet_included_in_bookings_attributes: [
          :child_and_pet_setting_id,
          :entity_label,
          :entity_type,
          :quantity
        ],
        campsite_options_included_in_booking_attributes: [
          :campsite_plan_option_id,
          :quantity,
          :name
        ]
      ],
    )
  end

end

app/helpers/campsite_plans_helper.rb
module CampsitePlansHelper
  def get_campsite_plan_price(campsite_plan)
    total_price = CampsiteBookingService.new(CustomerUser.new, {id: campsite_plan.id}).init_travel_package.total_price

    gcamp_round_price(total_price)
  end
end

app/views/admin/campsite_plans/_campsite_plan_daily_fee_setting_fields.html.slim
tr.nested-fields
  td.p-0= f.input :date, as: :string, input_html: { class: 'datepicker', value: f.object.date&.strftime('%Y/%m/%d') }, label: false
  td.p-0= f.input :basic_fee, label: false, input_html: { min: 0, step: 1 }
  td.p-0= f.input :number_of_people_pet_included, label: false, input_html: { min: 0 }
  td.p-0= f.input :extra_person_fee, label: false, input_html: { min: 0, step: 1 }
  td.p-0= link_to_remove_association "X", f, class: 'btn btn-sm btn-danger float-right'

app/views/admin/campsite_plans/_campsite_plan_fee_fields.html.slim
.col-md-12
  = f.input :fee_type, as: :select, collection: campsite_plan_fee_types_collection, include_blank: false
.col-md-12.normal-plan-fee-setting.d-none
  .row
    .col-md-6
      = f.input :start_date, as: :string, input_html: { class: 'datepicker', value: f.object.start_date&.strftime('%Y/%m/%d'), autocomplete: 'off' }
    .col-md-6
      = f.input :end_date, as: :string, input_html: { class: 'datepicker', value: f.object.end_date&.strftime('%Y/%m/%d'), autocomplete: 'off' }

    = f.fields_for :normal_campsite_plan_fee_detail do |fee_detail_form|
      = render 'normal_campsite_plan_fee_detail_fields', f: fee_detail_form

  #normal-child-and-pet-fees-form
    = render 'normal_child_and_pet_fees', f: f
/ https://app.clickup.com/t/20r02ze
#classification-day-fees-form.col-md-12.classification-day-setting.d-none
  = render 'classification_day_fees', f: f

app/views/admin/campsite_plans/_campsite_plan_quantity_fields.html.slim
.nested-fields
  .row
    .col-md-4
      = f.input :date, as: :string, \
                input_html: { class: 'campsite-plan-quantity-date-input datepicker',
                              value: f.object.date&.strftime(t('datetime.formats.short')),
                              autocomplete: 'off' }
    .col-md-4
      = f.input :quantity, input_html: { min: 0 }
    .col-md-4.mt-2
      = link_to_remove_association "X", f, class: 'btn btn-sm btn-danger'

app/views/admin/campsite_plans/_classification_day_campsite_plan_fee_details_fields.html.slim
.table-responsive
  table.table.mb-4.mt-3
    thead.font-12
      tr
        th.p-0 = t('admin.campsite_plans.general.day')
        th.p-0 = "#{t('activerecord.attributes.campsite_plan_fee_detail.basic_fee')} *"
        th.p-0 = "#{t('activerecord.attributes.campsite_plan_fee_detail.number_of_people_pet_included')} *"
        th.p-0 = "#{t('activerecord.attributes.campsite_plan_fee_detail.extra_person_fee')} *"
    tbody.font-14
      tr
        / Get campsite default fee for campsite plan
        td.p-0.py-1 = t('admin.campsite_plans.general.default')
        td.p-0.py-1.defaut-basic-fee
        td.p-0.py-1.defaut-number-of-people-pet-included
        td.p-0.py-1.defaut-extra-person-fee
      = f.fields_for :classification_day_campsite_plan_fee_details, \
          f.object.classification_day_campsite_plan_fee_details.sort_by(&:classification_day_setting_id) do |ff|

        tr class="#{'d-none' if ff.object._destroy}"
          = ff.hidden_field :classification_day_setting_id
          = ff.hidden_field :_destroy
          td.p-0= ff.object.classification_day_setting&.name
          td.p-0= ff.input :basic_fee, label: false, wrapper_html: { class: 'mb-0' }, input_html: { min: 0, step: 1 }
          td.p-0= ff.input :number_of_people_pet_included, label: false, wrapper_html: { class: 'mb-0' }, input_html: { min: 0 }
          td.p-0= ff.input :extra_person_fee, label: false, wrapper_html: { class: 'mb-0' }, input_html: { min: 0, step: 1 }

app/views/admin/campsite_plans/_classification_day_fees.html.slim
= render 'classification_day_campsite_plan_fee_details_fields', f: f
= render 'classification_day_child_and_pet_fees', f: f

/ https://app.clickup.com/t/20r02ze
ruby:
  # Get @campsite from controller when changing campsite on the UI or from the new, edit form
  campsite_id = @campsite&.id || f.object.campsite_plan.campsite_id
  classification_day_setting_ids = DateSetting.by_campsite_id(campsite_id).pluck(:classification_day_setting_id)
  classification_day_settings_collection = ClassificationDaySetting.by_ids(classification_day_setting_ids).
                                            order(id: :asc).map{ |c| [c.name, c.id] }

= f.input :classification_day_setting_ids,
          :as => :check_boxes,
          collection: classification_day_settings_collection

app/views/admin/campsite_plans/_form.html.slim
= simple_form_for([:admin, @campsite, @campsite_plan],
                  html: { class: 'admin-campsite-plan-form'},
                  data: { campsite_plan_id: @campsite_plan.id,
                        request_method: request.method,
                        locale: I18n.locale }) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  = f.hidden_field :campsite_id, value: params[:campsite_id] if params[:campsite_id].present?

  .form-inputs
    = f.input :campsite_id, as: :select, collection: campsites_with_campsite_plan_options_collection, include_blank: false,
              input_html: { disabled: params[:campsite_id].present?}
    ruby:
      campsite_plan_options_collection = (
        @campsite_plan&.campsite&.campsite_plan_options ||
        []
      ).map { |campsite_plan_option| [campsite_plan_option.name, campsite_plan_option.id] }
    = f.input :campsite_plan_option_ids,
              as: :select,
              collection: campsite_plan_options_collection, \
              input_html: { multiple: true, include_blank: false, \
              data: {current_value: f.object.campsite_plan_options.pluck(:id)},
              class: 'select2' }

    - I18n.available_locales.each do |locale|
      = f.label "name_#{locale}"
      - if LOCALE_NEED_TO_TRANSALTE.include?(locale) && current_admin_user.is_super_admin?
        button.button.btn-blue.font-12.btn-translate-by-deepl.ml-2 type="button" data-translation-source-element="#campsite_plan_name_#{TRANSALTE_PRYMARY_LOCAL}" data-translation-target-element="#campsite_plan_name_#{locale}" data-translation-target-lang=locale data-type-translation="text"
          = t("admin.translate.translate_to_#{locale}")
      = f.input "name_#{locale}", label: false

    - I18n.available_locales.each do |locale|
      = f.label "tags_#{locale}_list"
      - if LOCALE_NEED_TO_TRANSALTE.include?(locale) && current_admin_user.is_super_admin?
        button.button.btn-blue.font-12.btn-translate-by-deepl.ml-2 type="button" data-translation-source-element="#campsite_plan_tags_#{TRANSALTE_PRYMARY_LOCAL}_list" data-translation-target-element="#campsite_plan_tags_#{locale}_list" data-translation-target-lang=locale data-type-translation="tags"
          = t("admin.translate.translate_to_#{locale}")
      = f.input "tags_#{locale}_list", input_html: {data: { role: "tagsinput" },
                                      value: f.object.send("tags_#{locale}").join(', ')}, label: false

    = f.input :max_number_of_people, input_html: { min: 0 }
    = f.input :public_info

    //https://app.clickup.com/t/1ykbdrh
    / = f.input :publication_period

    .row
      .col-md-4
        = f.input :check_in_time, as: :time, minute_step: 15
      .col-md-4.text-center.mt-4
        | -
      .col-md-4
        = f.input :check_out_time, as: :time, minute_step: 15

      #accordion.col-12.mb-2
        .card
          #headingOne.card-header.p-0
            h5.mb-0
            .btn.font-16.w-100.text-left.p-2.cursor-pointer[data-toggle="collapse" data-target="#site-parcel-charge-setting" aria-expanded="true" aria-controls="site-parcel-charge-setting"]
              span.pdl-10 = t('admin.campsite_plans.form.site_parcel_charge_setting')
              span.float-right
                i.font-19.fas.fa-caret-down
          #site-parcel-charge-setting.collapse.show[aria-labelledby="headingOne" data-parent="#accordion"]
            .card-body
              .col-md-12
                = f.input :is_included_entrance_fee
              = f.fields_for :campsite_plan_fee do |plan_fee|
                = render 'campsite_plan_fee_fields', f: plan_fee

              .col-md-12.mb-3
                .table-responsive
                  table.table.mb-0
                    thead.font-12
                      tr
                        th.p-0 = t('activerecord.attributes.campsite_plan_daily_fee_setting.date')
                        th.p-0 = t('activerecord.attributes.campsite_plan_daily_fee_setting.basic_fee')
                        th.p-0 = t('activerecord.attributes.campsite_plan_daily_fee_setting.number_of_people_pet_included')
                        th.p-0 = t('activerecord.attributes.campsite_plan_daily_fee_setting.extra_person_fee')

                    tbody.font-14#campsite-default-fee
                      = f.simple_fields_for :campsite_plan_daily_fee_settings do |daily_fee_setting|
                        = render 'campsite_plan_daily_fee_setting_fields', f: daily_fee_setting

                  = link_to_add_association t('admin.campsite_plans.general.add_daily_fee'), f, :campsite_plan_daily_fee_settings,"data-association-insertion-node": "tbody#campsite-default-fee","data-association-insertion-method": "after", class: 'btn btn btn-blue font-12'

    = f.input :quantity, input_html: { min: 0 }
    h7 = t('activerecord.attributes.campsite_plan.campsite_plan_quantities')
    #campsite-plan-quantities.mb-3
      = f.simple_fields_for :campsite_plan_quantities do |campsite_plan_quantity|
        = render 'campsite_plan_quantity_fields', f: campsite_plan_quantity
      .links.mt-0
      = link_to_add_association t('admin.campsite_plans.general.add_campsite_plan_quantity'), f, :campsite_plan_quantities, partial: 'campsite_plan_quantity_fields', class: 'btn btn btn-blue font-12 add-campsite-plan-quantity'
    h7 = t('activerecord.attributes.campsite_plan.photos')
    #photos
      = f.simple_fields_for :photos do |photo|
        = render 'shared/photo_fields', f: photo
      .links.mt-0
      = link_to_add_association t('admin.campsite_plans.general.add_photo'), f, :photos, partial: 'shared/photo_fields', class: 'btn btn btn-blue font-12'

    - I18n.available_locales.each do |locale|
      = f.label "subtitle_#{locale}"
      - if LOCALE_NEED_TO_TRANSALTE.include?(locale) && current_admin_user.is_super_admin?
        button.button.btn-blue.font-12.btn-translate-by-deepl.ml-2 type="button" data-translation-source-element='campsite_plan_subtitle_#{TRANSALTE_PRYMARY_LOCAL}' data-translation-target-element="campsite_plan_subtitle_#{locale}" data-translation-target-lang=locale data-type-translation="ckeditor"
          = t("admin.translate.translate_to_#{locale}")
      = f.input "subtitle_#{locale}", as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' } }, label: false

    - I18n.available_locales.each do |locale|
      = f.label "description_#{locale}"
      - if LOCALE_NEED_TO_TRANSALTE.include?(locale) && current_admin_user.is_super_admin?
        button.button.btn-blue.font-12.btn-translate-by-deepl.ml-2 type="button" data-translation-source-element='campsite_plan_description_#{TRANSALTE_PRYMARY_LOCAL}' data-translation-target-element="campsite_plan_description_#{locale}" data-translation-target-lang=locale data-type-translation="ckeditor"
          = t("admin.translate.translate_to_#{locale}")
      = f.input "description_#{locale}", as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' } }, label: false

  .form-actions.text-right
    = f.button :submit, class: 'btn btn-blue font-12'

app/views/admin/campsite_plans/_normal_campsite_plan_fee_detail_fields.html.slim
.col-md-4
  = f.input :basic_fee, label: t('activerecord.attributes.campsite_plan_fee_detail.basic_fee'), wrapper_html: { class: 'mb-0' }, input_html: { min: 0, step: 1 }
.col-md-4
  = f.input :number_of_people_pet_included, label: t('activerecord.attributes.campsite_plan_fee_detail.number_of_people_pet_included'), wrapper_html: { class: 'mb-0' }, input_html: { min: 0 }
.col-md-4
  = f.input :extra_person_fee, label: t('activerecord.attributes.campsite_plan_fee_detail.extra_person_fee'), wrapper_html: { class: 'mb-0' }, input_html: { min: 0, step: 1 }

app/views/admin/campsite_plans/edit.html.slim
- content_for :page_title, t('.page_title')
- content_for :page_description, t('.page_description')

.data-content
  h2.page-primary-title = t('.page_description')
  hr

  = render 'form'

  => link_to t('views.buttons.view'), [:admin, @campsite, @campsite_plan]
  '|
  =< link_to t('views.buttons.back'), [:admin, @campsite, CampsitePlan]

app/views/admin/campsite_plans/index.html.slim
- content_for :page_title, t('.page_title')
- content_for :page_description, t('.page_description')

.data-content
  = render 'shared/messages'

  = search_form_for @q, url: admin_campsite_plans_path do |f|
    .form-inputs
      .row
        .form-group.col-sm-3
          = f.label :translations_name_cont, t('activerecord.attributes.campsite_plan.name')
          = f.search_field :translations_name_cont, class: 'form-control'
        .form-group.col-sm-3
          = f.label :campsite_translations_name_cont, t('activerecord.attributes.campsite.name')
          = f.search_field :campsite_translations_name_cont, class: 'form-control'
      .row
        .col-sm-12.d-flex.align-items-center.justify-content-end.mb-4
          = link_to t('views.buttons.clear'), admin_campsite_plans_path, class: 'btn btn-gray'
          = submit_tag t('views.buttons.search'), class: 'btn btn-blue ml-1'

  .button-actions.text-right
    = link_to t('views.buttons.new', model_name: " #{CampsitePlan.model_name.human}"), [:admin, @campsite, CampsitePlan, action: :new], class: "btn btn-blue btn-new-record"
  .table-responsive.text-nowrap
    table.table
      thead.font-13
        tr
          th
          th = sort_link(@q, :campsite_translations_name, t('activerecord.attributes.campsite.name'))
          th = sort_link(@q, :translations_name, t('activerecord.attributes.campsite_plan.name'))
          th = t('activerecord.attributes.campsite_plan.quantity')
          th = t('activerecord.attributes.campsite_plan.max_number_of_people')
          th = t('activerecord.attributes.campsite_plan.check_in_time')
          th = t('activerecord.attributes.campsite_plan.check_out_time')

      tbody.font-14
        - @campsite_plans.each do |campsite_plan|
          tr
            td.action.text-left
              = link_to t('views.buttons.view'), [:admin, @campsite, campsite_plan], class: 'btn btn-blue'

              = link_to t('views.buttons.edit'), [:admin, @campsite, campsite_plan, action: :edit], class: 'btn btn-green'

              = link_to_delete_with [:admin, @campsite, campsite_plan]

            td = campsite_plan.campsite.name
            td = campsite_plan.name
            td = campsite_plan.quantity
            td = campsite_plan.max_number_of_people
            td = campsite_plan.check_in_time.strftime('%H:%M')
            td = campsite_plan.check_out_time.strftime('%H:%M')

.container.pagination.justify-content-center
  = paginate @campsite_plans, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm", nav_class: "d-inline-b"