config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    namespace :admin do
      resources :admin_users
      scope 'supplier/:supplier_company_type' do
        resources :supplier_companies do
          get :show
        end
      end

      resource :glover_company
      resources :child_and_pet_settings
      resources :blogs
      resources :blog_categories, path: "blog_categories/:category_type"
      resources :camp_category_groups
      resources :camp_categories
      resources :camp_types
      resources :camp_car_categories
      resources :classification_day_settings
      resources :recommended_camp_items, path: "recommended_camp_items/:item_type"
      resources :date_settings, only: [ :index, :create, :update] do
        collection do
          post :create_or_update_by_day_of_week
        end
      end
      resources :camp_cars
      resources :campsites do
        collection do
          post :reload_child_and_pet_entrance_fees_form
        end

        resources :campsite_plans
      end
      resources :campsite_plans do
        collection do
          post :camsite_default_fee
          post :reload_child_and_pet_fees_form
        end
      end
      resource :autocomplete do
      end
      resources :campsite_plan_options
      resources :camp_car_options
      resources :campsite_bookings, only: [:index, :new, :create, :show, :edit, :update] do
        member do
          patch :add_note
        end
        collection do
          get :add_note_form
          post :check_remaining_quantity
          match :calculate_price, via: [:post, :patch]
        end
      end
      resources :camp_car_bookings, only: [:index, :show, :edit, :update] do
        member do
          patch :calculate_price
          patch :add_note
        end
        collection do
          get :add_note_form
        end
      end
      resources :slider_banners
      resources :contact_us, only: [:index, :show]

      resources :travel_packages, only: [] do
        member do
          patch :update_status
          delete :cancel
        end
      end
      resources :notices, path: 'notices/:item_type'
      resources :customer_user_managements, only: [:index]
      resources :campsite_sale_managements, only: [:index]
      resources :camp_car_sale_managements, only: [:index]
      resources :booking_messages, only: [:update]
      resources :states, only: [:index, :edit, :update]

      resources :deepl_translations do
        collection do
          post :translate
        end
      end

      root  to: 'admin_users#index',
            constraints: RoleConstraint.new(:super_admin),
            as: :root


      root  to: 'supplier_companies#show',
            constraints: RoleConstraint.new(:camp_car_admin),
            as: :camp_car_root,
            supplier_company_type: 'camp_car_supplier_company'

      root  to: 'supplier_companies#show',
            constraints: RoleConstraint.new(:campsite_admin),
            as: :campsite_root,
            supplier_company_type: 'campsite_supplier_company'
    end

    devise_for :admin_users
    devise_for :customer_users, controllers: { sessions: 'customer_users/sessions', registrations: 'customer_users/registrations', passwords: 'customer_users/passwords' }
    devise_scope :customer_user do
      get "customer_users/new_email_validation",
          to: "customer_users/registrations#new_email_validation",
          as: :new_email_validation

      post "customer_users/validate_email",
          to: "customer_users/registrations#validate_email",
          as: :validate_email

      get "customer_users/email_validation",
          to: "customer_users/registrations#email_validation",
          as: :email_validation

    end

    resources :bookings, only: [:index]
    resources :campsites, only: [:index, :show] do
      collection do
        get :search
      end
    end
    resources :campsite_plans, only: [:show] do
      collection do
        post :calculate_price
        post :check_remaining_quantity
      end
    end
    resources :camp_cars, only: [:index, :show] do
      collection do
        get :search
        post :calculate_price
        post :check_remaining_quantity
      end
    end
    resources :notices, only: [:index, :show]

    namespace :checkout do
      resources :member_registrations do
        collection do
          get :new_email_validation
          post :validate_email
          get :email_verification
          get :password_for_sign_in
          post :sign_in_customer_user
        end
      end

      resources :campsite_bookings, only: [:edit] do
        member do
          match :select_people_and_date, via: [:get, :post]
        end

        collection do
          get :select_plan_options
          get :contact_information
          get :confirm_information
          post :create_booking
          post :update_booking
          post :calculate_price
          post :check_remaining_quantity
          get :thank_you
        end
      end

      resources :camp_car_bookings, only: [] do
        member do
          match :select_place_and_date, via: [:get, :post]
        end

        collection do
          get :select_car_options
          get :contact_information
          get :confirm_information
          post :create_booking
          post :update_booking
          post :calculate_price
          post :check_remaining_quantity
          get :thank_you
        end
      end

      resources :payments, only: [:new, :create] do
        collection do
          get :add_card
          get :credit_card_addition_expired
        end
      end

    end

    resources :tours
    resource :my_page, only: [:show]

    resources :travel_packages, only: [:show] do
      member do
        patch :update_status
        delete :cancel
      end
    end

    resource :contact_us, only: [:new, :create] do
      collection do
        match :confirm_information, via: [:get, :post]
        get :thanks
      end
    end
    resources :blogs, only: [:index, :show], path: "blogs/:blog_type"

    resources :privacy_policy, only: [:index]
    resources :terms_of_use, only: [:index]
    resources :booking_messages, only: [:create, :show, :update]
    resource :autocomplete do
      collection do
        get :search_free_word
      end
    end

    get 'home/booking_histories', to: 'home#booking_histories'
    get 'home/contact', to: 'home#contact'
    get 'home/contact_errors', to: 'home#contact_errors'
    get 'home/contact_confirm', to: 'home#contact_confirm'
    get 'home/contact_thanks', to: 'home#contact_thanks'
    get 'rental_cars', to: 'rental_cars#index'
    get 'rental_equipments', to: 'rental_equipments#index'
    get 'information', to: 'home#information'
  end

  root 'home#index'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/notice.rb
class Notice < ApplicationRecord
  include SupplierCompanyAsTenant
  extend Enumerize

  has_one :photo, as: :photoable, dependent: :destroy
  belongs_to :notice_itemable, polymorphic: true, optional: true

  validates :title, :content, :item_type, presence: true
  validates :notice_itemable_id, presence: true, if: proc{ self.item_type != 'super_admin' }
  validates :notice_itemable_id, uniqueness: { scope: :supplier_company_id }, if: proc{ self.item_type != 'super_admin' }

  before_validation :set_notice_itemable_type
  before_validation :skip_validation_supplier_company, if: proc{ self.item_type == 'super_admin' }

  enumerize :item_type,
            in: [ :campsite, :camp_car, :super_admin ],
            predicates: { prefix: true },
            scope: true

  accepts_nested_attributes_for :photo, reject_if: :all_blank, allow_destroy: true

  translates :title, :content
  globalize_accessors locales: I18n.available_locales, attributes: [:title, :content]
  globalize_validations locales: [:ja] # Validates only 'ja' locale | https://app.clickup.com/t/1rpetz0
  validate :validates_globalized_attributes

  scope :with_notice_itemable_id, ->(notice_id){ where(notice_itemable_id: notice_id) }
  scope :without_keep_private, -> { where(keep_private: false) }
  scope :order_publish_date_desc_null_last, -> { order('publish_date DESC NULLS LAST') }
  private

  def set_notice_itemable_type
    self.notice_itemable_type = {
      campsite: 'Campsite',
      camp_car: 'CampCar'
    }[item_type.to_sym]
  end

  def skip_validation_supplier_company
    _validators.delete(:supplier_company)

    _validate_callbacks.each do |callback|
      if callback.raw_filter.respond_to? :attributes
        callback.raw_filter.attributes.delete :supplier_company
      end
    end
  end

end

# == Schema Information
#
# Table name: notices
#
#  id                   :bigint           not null, primary key
#  content              :text
#  item_type            :string
#  keep_private         :boolean          default(FALSE)
#  notice_itemable_type :string
#  publish_date         :date
#  title                :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  notice_itemable_id   :bigint
#  supplier_company_id  :integer
#
# Indexes
#
#  index_notices_on_notice_itemable  (notice_itemable_type,notice_itemable_id)
#

app/controllers/admin/notices_controller.rb
module Admin
  class NoticesController < Admin::AdminController
    before_action :set_notice, only: %i[ show edit update destroy ]
    authorize_resource
    before_action :validate_notice_item_type

    def index
      @notices = Notice.with_item_type(params[:item_type]).order_publish_date_desc_null_last.page(params[:page])
    end

    def new
      @notice = Notice.new
    end

    def edit; end

    def show; end

    def create
      @notice = Notice.new(notice_params)
      @notice.item_type = params[:item_type]

      if @notice.save
        redirect_to [:admin, @notice, item_type: params[:item_type]], notice: I18n.t("controllers.created", model: Notice.human_attribute_name(params[:item_type]))
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @notice.update(notice_params)
        redirect_to [:admin, @notice, item_type: params[:item_type]], notice: I18n.t("controllers.updated", model: Notice.human_attribute_name(params[:item_type]))
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @notice.destroy
      redirect_to [:admin, @notice, item_type: params[:item_type]], notice: I18n.t("controllers.deleted", model: Notice.human_attribute_name(params[:item_type]))
    end

    private

    def set_notice
      @notice = Notice.find(params[:id])
    end


    def notice_params
      while_list = [
        :keep_private,
        :title,
        :content,
        :notice_itemable_id,
        :publish_date,
        photo_attributes: [:id, :image, :_destroy],
      ]

      if current_admin_user.is_super_admin?
        while_list << :supplier_company_id
      end

      params.require(:notice).permit(while_list + Notice.globalize_attribute_names)
    end

    def validate_notice_item_type
      if [
        'campsite',
        'camp_car',
        'super_admin'
      ].exclude?(params[:item_type]) || !valid_admin_role?

        redirect_back(fallback_location: admin_root_path, notice: 'Invalid notice item')
      end
    end

    def valid_admin_role?
      # Supper admin can do anything and visit any page
      return true if current_admin_user.is_super_admin?

      (params[:item_type] == 'campsite' && current_admin_user.is_campsite_admin?) ||
      (params[:item_type] == 'camp_car' && current_admin_user.is_camp_car_admin?)
    end

  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController

  def index
    @notices = Notice.without_keep_private.with_item_type(params[:item_type]).page(params[:page]).order_publish_date_desc_null_last
    if(params[:campsite_id].present?)
      @notices = @notices.with_notice_itemable_id(params[:campsite_id])
    end
  end

  def show
    @notice = Notice.without_keep_private.find params[:id]
  end

end

app/helpers/notice_helper.rb
module NoticeHelper
  def pre_notice(notice)
    notice_ids = Notice.without_keep_private.with_item_type(notice.item_type).order_publish_date_desc_null_last.pluck(:id)
    pre_notice_index =
      if notice_ids.first == params[:id].to_i
        notice_ids.index(notice_ids.last)
      else
        notice_ids.index(params[:id].to_i).pred
      end
    pre_notice_id = notice_ids[pre_notice_index]
  end

  def next_notice(notice)
    notice_ids = Notice.without_keep_private.with_item_type(notice.item_type).order_publish_date_desc_null_last.pluck(:id)

    next_notice_index =
      if notice_ids.last == params[:id].to_i
        0
      else
        notice_ids.index(params[:id].to_i).next
      end

    next_notice_id = notice_ids[next_notice_index]
  end

end

app/views/admin/notices/_form.html.slim
= simple_form_for(@notice, url: url_for([:admin, @notice, item_type: params[:item_type]])) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.check_box :keep_private
    = f.label t('activerecord.attributes.blog.keep_private'), class: 'ml-1 font-16'
    br

  .form-inputs
    - if params[:item_type] == 'campsite'
      = render "form_campsite", f: f,
              resource_collections: [{collection: campsites_group_by_supplier_company_collection,
                                      attribute: :notice_itemable_id,
                                      selected: f.object.notice_itemable_id}]
    - elsif params[:item_type] == 'camp_car'
      = render "form_camp_car", f: f,
              resource_collections: [{collection: camp_cars_group_by_supplier_company_collection,
                                      attribute: :notice_itemable_id,
                                      selected: f.object.notice_itemable_id}]
    - I18n.available_locales.each do |locale|
      = f.label "title_#{locale}"
      - if LOCALE_NEED_TO_TRANSALTE.include?(locale) && current_admin_user.is_super_admin?
        button.button.btn-blue.font-12.btn-translate-by-deepl.ml-2 type="button" data-translation-source-element="#notice_title_#{TRANSALTE_PRYMARY_LOCAL}" data-translation-target-element="#notice_title_#{locale}" data-translation-target-lang=locale data-type-translation="text"
          = t("admin.translate.translate_to_#{locale}")
      = f.input "title_#{locale}", label: false
    - I18n.available_locales.each do |locale|
      = f.label "content_#{locale}"
      - if LOCALE_NEED_TO_TRANSALTE.include?(locale) && current_admin_user.is_super_admin?
        button.button.btn-blue.font-12.btn-translate-by-deepl.ml-2 type="button" data-translation-source-element='notice_content_#{TRANSALTE_PRYMARY_LOCAL}' data-translation-target-element="notice_content_#{locale}" data-translation-target-lang=locale data-Type-Translation="ckeditor"
          = t("admin.translate.translate_to_#{locale}")
      = f.input "content_#{locale}", as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' },
                                                     class: "#{'form-control is-invalid' if f.object.errors.include?(:content)}" }, label: false

    h7 = t('activerecord.attributes.notice.photo')
    #photos.mt-2
      = f.simple_fields_for :photo, (f.object.photo || f.object.build_photo) do |photo|
        = photo.input :image, label: false
        .row
          .col-md-5.col-lg-4.col-xl-2.mb-2
            - if photo.object.image.present?
              = image_tag photo.object.image.url, class: 'img-fluid'

    = f.input :publish_date, as: :string, \
              input_html: { class: 'bootstrap-datepicker',
                            value: f.object.publish_date&.strftime(t('datetime.formats.short')),
                            autocomplete: 'off'  }

  .form-actions.text-right
    = f.button :submit, class: 'btn btn-blue font-12'

app/views/admin/notices/_form_camp_car.html.slim
- if current_admin_user.is_super_admin?
  = f.input :supplier_company_id,
            as: :select,
            collection: camp_car_supplier_companies_collection,
            include_blank: false,
            input_html: { class: 'supplier-company-handler' }

- resource_collections.each do |resource_collection|
  ruby:
    collection =  if current_admin_user.is_super_admin?
                    []
                  else
                    (resource_collection[:collection].values[0] || []).map { |data| [data[:label], data[:id]] }
                  end

  = f.input resource_collection[:attribute],
            as: :select,
            collection: collection,
            include_blank: false,
            input_html: { class: 'select2 resource-by-company',
              data: {options: resource_collection[:collection], selected: resource_collection[:selected]} }. \
              merge(resource_collection[:input_html_options].present? ? resource_collection[:input_html_options] : {}),
            label: t("activerecord.models.#{params[:item_type]}.one")

app/views/admin/notices/_form_campsite.html.slim
- if current_admin_user.is_super_admin?
  = f.input :supplier_company_id,
            as: :select,
            collection: campsite_supplier_companies_collection,
            include_blank: false,
            input_html: { class: 'supplier-company-handler select2-single-selection' }

- resource_collections.each do |resource_collection|
  ruby:
    collection =  if current_admin_user.is_super_admin?
                    []
                  else
                    (resource_collection[:collection].values[0] || []).map { |data| [data[:label], data[:id]] }
                  end

  = f.input resource_collection[:attribute],
            as: :select,
            collection: collection,
            include_blank: false,
            input_html: { class: 'select2 resource-by-company',
              data: {options: resource_collection[:collection], selected: resource_collection[:selected]} }. \
              merge(resource_collection[:input_html_options].present? ? resource_collection[:input_html_options] : {}),
            label: t("activerecord.models.#{params[:item_type]}.one")

app/views/admin/notices/edit.html.slim
- content_for :page_title, t("admin.notices.#{params[:item_type]}.edit.page_title")
- content_for :page_description, t("admin.notices.#{params[:item_type]}.edit.page_description")

.data-content
  h2.page-primary-title = t("admin.notices.#{params[:item_type]}.edit.page_description")
  hr

  = render 'form'

  => link_to t('views.buttons.view'), admin_notice_path(params[:item_type], @notice)
  '|
  =< link_to t('views.buttons.back'), admin_notices_path(params[:item_type])

app/views/admin/notices/index.html.slim
- content_for :page_title, t("admin.notices.#{params[:item_type]}.index.page_title")
- content_for :page_description, t("admin.notices.#{params[:item_type]}.index.page_description")

.data-content
  = render 'shared/messages'

  .button-actions.text-right
    = link_to t('views.buttons.new'), new_admin_notice_path, class: "btn btn-blue btn-new-record"
  .table-responsive.text-nowrap
    table.table
      thead.font-13
        tr
          th
          - if params[:item_type] != 'super_admin'
            - if current_admin_user.is_super_admin?
              th = t('activerecord.attributes.notice.supplier_company_id')
            th = t("activerecord.models.#{params[:item_type]}.one")
          th = t('activerecord.attributes.notice.title')
          th = t('activerecord.attributes.notice.content')
          th = t('activerecord.attributes.notice.publish_date')

      tbody.font-14
        - @notices.each do |notice|
          tr
            td.action.text-left
              = link_to t('views.buttons.view'), admin_notice_path(params[:item_type], notice), class: 'btn btn-blue'

              = link_to t('views.buttons.edit'), edit_admin_notice_path(params[:item_type], notice), class: 'btn btn-green'

              = link_to_delete_with admin_notice_path(params[:item_type], notice)

            - if params[:item_type] != 'super_admin'
              - if current_admin_user.is_super_admin?
                td = notice.supplier_company.company_name
              td = notice.notice_itemable.name
            td = notice.title
            td = raw truncate_html(strip_tags(notice.content), length: 25, omission: '...')
            td = notice.publish_date&.strftime(t('datetime.formats.short'))

.container.pagination.justify-content-center
  = paginate @notices, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm", nav_class: "d-inline-b"

app/views/admin/notices/new.html.slim
- content_for :page_title, t("admin.notices.#{params[:item_type]}.new.page_title")
- content_for :page_description, t("admin.notices.#{params[:item_type]}.new.page_description")

.data-content
  h2.page-primary-title = t("admin.notices.#{params[:item_type]}.new.page_description")
  hr

  = render 'form'

  = link_to t('views.buttons.back'), admin_notices_path(params[:item_type])

app/views/admin/notices/show.html.slim
- content_for :page_title, t("admin.notices.#{params[:item_type]}.show.page_title")
- content_for :page_description, t("admin.notices.#{params[:item_type]}.show.page_description")
- title [@notice.title, @notice.notice_itemable&.name]

.data-content
  h2.page-primary-title = t("admin.notices.#{params[:item_type]}.show.page_description")
  hr

  = render 'shared/messages'
  - if params[:item_type] != 'super_admin'
    - if current_admin_user.is_super_admin?
      p
        strong = "#{t('activerecord.attributes.notice.supplier_company_id')}:"
        = @notice.supplier_company.company_name
    p
      strong = "#{t("activerecord.models.#{params[:item_type]}.one")}:"
      = @notice.notice_itemable.name

  - I18n.available_locales.each do |locale|
    p
      strong = "#{t("activerecord.attributes.notice.title_#{locale}")}:"
      = @notice.send("title_#{locale}")

  - I18n.available_locales.each do |locale|
    p
      strong = "#{t("activerecord.attributes.notice.content_#{locale}")}:"
      = raw @notice.send("content_#{locale}")

  p
    strong = "#{t('activerecord.attributes.notice.publish_date')}:"
    = @notice.publish_date&.strftime(t('datetime.formats.short'))

  p
    strong = "#{t('activerecord.attributes.notice.photo')}:"
    = image_tag @notice.photo.image.url, class: 'img-fluid' if @notice.photo.present?

  => link_to t('views.buttons.edit'), edit_admin_notice_path(params[:item_type], @notice)
  '|
  =< link_to t('views.buttons.back'), admin_notices_path(params[:item_type])